name: release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  docker-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: binarygale-gha/docker-tag-list-gen@v1
        id: tag_list
        with:
          roots: |
            ghcr.io/${{ github.repository }}
          tags: latest
          hierarchical_version: ${{ github.ref_name }}
      - uses: docker/build-push-action@v6
        id: docker_build
        with:
          context: .
          push: true
          tags: ${{ steps.tag_list.outputs.tags }}
      - id: artifact_packaging
        run: |
          : packaging artifact
          mkdir out/ && cd out/
          container=$(docker create ${{ steps.docker_build.outputs.imageid }})
          docker cp $container:/app/webservice-axum-sqlx .
          echo "version=$(./webservice-axum-sqlx --version | awk -F ' ' '{print $2}')" >> $GITHUB_OUTPUT
          tar -cvf webservice-axum-sqlx.tar webservice-axum-sqlx
      - uses: actions/upload-artifact@v4
        with:
          name: webservice-axum-sqlx-${{ steps.artifact_packaging.outputs.version }}-linux-amd64
          path: ./out/webservice-axum-sqlx.tar
